input { 
  beats {
    port => 5044
  }
}
filter {
  if "apache" in [tags] {
    grok {
        match => { "message" => "%{COMBINEDAPACHELOG}"}
    }
  } else if "csv" in [tags] {
		csv {
			columns => ["country","city","accentCity","region","population"]
		}		
		mutate {
			add_field => {
				"location" => "%{column6},%{column7}"
			} 
			remove_field => [ "message", "@version","@timestamp","host","path","column6","column7" ]	
		}
	}
}
output {
  if "apache" in [tags] {
    elasticsearch {
        index => "apache-logs"
        hosts => "elasticsearch:9200"
        user => "elastic"
        password => "changeme"
        ecs_compatibility => disabled
    }
  } else 	if "csv" in [tags] {
    stdout { codec => rubydebug }
    elasticsearch {
      index => "cities"
      hosts => "elasticsearch:9200"
      user => "elastic"
      password => "changeme"
      ecs_compatibility => disabled
    }
  }
}